import { Incident, District, CrimeType } from './types';

export const DISTRICTS: District[] = [
  'Central',
  'North',
  'South',
  'Cyber City',
  'West Outer',
  'Tech Hub',
  'Harbour',
  'East District',
];

export const CRIME_TYPES: CrimeType[] = [
  'Cyber Fraud / Financial',
  'Vehicle Theft',
  'Burglary / Breaking-in',
  'Robbery / Snatching',
  'Assault / Grievous Hurt',
  'Narcotics / NDPS',
  'Public Nuisance & Gambling',
];

export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

// Reference base coordinates (Metropolitan Grid)
const DISTRICT_COORDS: Record<District, { lat: number; lng: number }> = {
  Central: { lat: 28.6328, lng: 77.2197 },
  North: { lat: 28.6942, lng: 77.2104 },
  South: { lat: 28.5355, lng: 77.2410 },
  'Cyber City': { lat: 28.4900, lng: 77.0880 },
  'West Outer': { lat: 28.6500, lng: 77.0600 },
  'Tech Hub': { lat: 28.4595, lng: 77.0266 },
  Harbour: { lat: 28.5800, lng: 77.3100 },
  'East District': { lat: 28.6280, lng: 77.2950 },
};

export const MOCK_INCIDENTS: Incident[] = [
  {
    fir_id: 'FIR-2024-08912',
    date: '2024-11-14',
    district: 'Cyber City',
    crime_type: 'Cyber Fraud / Financial',
    hour: 23,
    day_of_week: 'Thursday',
    is_weekend: false,
    latitude: 28.4912,
    longitude: 77.0894,
    description: 'Victim targeted via social engineering and cloned SIM request at late night, transferring unauthorized sum to mule account network.',
    location_name: 'Sector 29 Financial Enclave',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-08918',
    date: '2024-11-15',
    district: 'Cyber City',
    crime_type: 'Cyber Fraud / Financial',
    hour: 2,
    day_of_week: 'Friday',
    is_weekend: false,
    latitude: 28.4880,
    longitude: 77.0910,
    description: 'ATM skimming device detected at midnight with duplicate card clone attempts on multiple corporate payroll accounts.',
    location_name: 'Cyber Greens Tower B',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09004',
    date: '2024-11-16',
    district: 'North',
    crime_type: 'Vehicle Theft',
    hour: 22,
    day_of_week: 'Saturday',
    is_weekend: true,
    latitude: 28.6920,
    longitude: 77.2130,
    description: 'Two-wheeler stolen from unlit residential perimeter parking using master key ignition bypass technique.',
    location_name: 'Model Town Ring Road',
    status: 'PENDING CHARGE',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09015',
    date: '2024-11-16',
    district: 'North',
    crime_type: 'Robbery / Snatching',
    hour: 23,
    day_of_week: 'Saturday',
    is_weekend: true,
    latitude: 28.6955,
    longitude: 77.2085,
    description: 'Two masked suspects on a dark motorcycle snatched handbag and smartphone from commuter near metro subway exit.',
    location_name: 'GTB Nagar Metro Gate 3',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09033',
    date: '2024-11-17',
    district: 'South',
    crime_type: 'Burglary / Breaking-in',
    hour: 3,
    day_of_week: 'Sunday',
    is_weekend: true,
    latitude: 28.5370,
    longitude: 77.2435,
    description: 'Forced entry via rear alley window into commercial jewelry showroom during low-traffic predawn hours.',
    location_name: 'Greater Kailash Main Market',
    status: 'COURT TRIAL',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09048',
    date: '2024-11-18',
    district: 'Central',
    crime_type: 'Robbery / Snatching',
    hour: 19,
    day_of_week: 'Monday',
    is_weekend: false,
    latitude: 28.6340,
    longitude: 77.2215,
    description: 'Gold chain snatched by pillion rider on motorcycle in crowded bazaar bottleneck during peak evening shopping transit.',
    location_name: 'Connaught Circle Inner Block',
    status: 'CLOSED',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09062',
    date: '2024-11-19',
    district: 'Tech Hub',
    crime_type: 'Cyber Fraud / Financial',
    hour: 14,
    day_of_week: 'Tuesday',
    is_weekend: false,
    latitude: 28.4610,
    longitude: 77.0280,
    description: 'Phishing portal impersonating state electricity bill payment portal gathered OTP credentials from senior citizen.',
    location_name: 'DLF Cyber Park Sector 20',
    status: 'UNDER INVESTIGATION',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09075',
    date: '2024-11-20',
    district: 'West Outer',
    crime_type: 'Vehicle Theft',
    hour: 1,
    day_of_week: 'Wednesday',
    is_weekend: false,
    latitude: 28.6520,
    longitude: 77.0580,
    description: 'Commercial delivery van hotwired and driven toward state border corridor with GPS tracker disabled.',
    location_name: 'Najafgarh Freight Terminal',
    status: 'CLOSED',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09091',
    date: '2024-11-21',
    district: 'Harbour',
    crime_type: 'Narcotics / NDPS',
    hour: 21,
    day_of_week: 'Thursday',
    is_weekend: false,
    latitude: 28.5815,
    longitude: 77.3120,
    description: 'Interception of contraband transit parcel hidden inside inter-state cargo consignment at logistics junction.',
    location_name: 'Noida-Okhla Freight Depot',
    status: 'COURT TRIAL',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09102',
    date: '2024-11-22',
    district: 'East District',
    crime_type: 'Assault / Grievous Hurt',
    hour: 23,
    day_of_week: 'Friday',
    is_weekend: false,
    latitude: 28.6295,
    longitude: 77.2970,
    description: 'Altercation between two groups near public night food stalls escalating to physical violence with blunt objects.',
    location_name: 'Laxmi Nagar Night Market',
    status: 'PENDING CHARGE',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09120',
    date: '2024-11-23',
    district: 'Central',
    crime_type: 'Public Nuisance & Gambling',
    hour: 20,
    day_of_week: 'Saturday',
    is_weekend: true,
    latitude: 28.6310,
    longitude: 77.2180,
    description: 'Unauthorized underground sports betting syndicate running inside basement club; equipment seized.',
    location_name: 'Paharganj Alley 4',
    status: 'CLOSED',
    priority: 'LOW'
  },
  {
    fir_id: 'FIR-2024-09134',
    date: '2024-11-23',
    district: 'North',
    crime_type: 'Robbery / Snatching',
    hour: 22,
    day_of_week: 'Saturday',
    is_weekend: true,
    latitude: 28.6970,
    longitude: 77.2110,
    description: 'Black motorcycle without registration plate intercepted pedestrian near park boundary and grabbed mobile device.',
    location_name: 'Civil Lines Northern Ridge',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09148',
    date: '2024-11-24',
    district: 'Cyber City',
    crime_type: 'Cyber Fraud / Financial',
    hour: 16,
    day_of_week: 'Sunday',
    is_weekend: true,
    latitude: 28.4890,
    longitude: 77.0870,
    description: 'Remote screen sharing malware application installed under guise of technical support for banking app update.',
    location_name: 'Golf Course Road Sector 43',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09160',
    date: '2024-11-25',
    district: 'South',
    crime_type: 'Vehicle Theft',
    hour: 4,
    day_of_week: 'Monday',
    is_weekend: false,
    latitude: 28.5340,
    longitude: 77.2390,
    description: 'Luxury SUV stolen using electronic key frequency repeater attack from residential driveway.',
    location_name: 'Vasant Vihar Block C',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09172',
    date: '2024-11-26',
    district: 'West Outer',
    crime_type: 'Burglary / Breaking-in',
    hour: 2,
    day_of_week: 'Tuesday',
    is_weekend: false,
    latitude: 28.6480,
    longitude: 77.0620,
    description: 'Lock tampering and shutter shuttering at electronics warehouse; inventory taken in unmarked pickup truck.',
    location_name: 'Janakpuri District Centre',
    status: 'PENDING CHARGE',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09185',
    date: '2024-11-27',
    district: 'East District',
    crime_type: 'Vehicle Theft',
    hour: 23,
    day_of_week: 'Wednesday',
    is_weekend: false,
    latitude: 28.6270,
    longitude: 77.2930,
    description: 'Sedan vehicle lifted from unmonitored hospital outdoor parking lot during night shift hours.',
    location_name: 'Mayur Vihar Phase 1',
    status: 'CLOSED',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09199',
    date: '2024-11-28',
    district: 'Central',
    crime_type: 'Cyber Fraud / Financial',
    hour: 11,
    day_of_week: 'Thursday',
    is_weekend: false,
    latitude: 28.6350,
    longitude: 77.2230,
    description: 'Fake investment crypto portal promising 30% daily returns defrauded retail investor of funds.',
    location_name: 'Barakhamba Road Plaza',
    status: 'UNDER INVESTIGATION',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09210',
    date: '2024-11-29',
    district: 'Tech Hub',
    crime_type: 'Assault / Grievous Hurt',
    hour: 22,
    day_of_week: 'Friday',
    is_weekend: false,
    latitude: 28.4580,
    longitude: 77.0250,
    description: 'Road rage incident following vehicle collision resulting in physical altercation and bodily injury.',
    location_name: 'Sohna Road Expressway Junction',
    status: 'COURT TRIAL',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09225',
    date: '2024-11-30',
    district: 'North',
    crime_type: 'Vehicle Theft',
    hour: 3,
    day_of_week: 'Saturday',
    is_weekend: true,
    latitude: 28.6960,
    longitude: 77.2120,
    description: 'Multiple motorcycles stolen in single night from metro parking lot with clipped perimeter chain.',
    location_name: 'Vishwa Vidyalaya Metro Complex',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09238',
    date: '2024-12-01',
    district: 'South',
    crime_type: 'Narcotics / NDPS',
    hour: 0,
    day_of_week: 'Sunday',
    is_weekend: true,
    latitude: 28.5360,
    longitude: 77.2420,
    description: 'Raid on private farmhouse party resulting in seizure of synthetic narcotics and unregistered imported alcohol.',
    location_name: 'Chattarpur Farm Zone',
    status: 'PENDING CHARGE',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09250',
    date: '2024-12-02',
    district: 'Harbour',
    crime_type: 'Burglary / Breaking-in',
    hour: 4,
    day_of_week: 'Monday',
    is_weekend: false,
    latitude: 28.5790,
    longitude: 77.3080,
    description: 'Commercial godown shutter lock cut using gas torch; copper coils and industrial cables removed.',
    location_name: 'Okhla Industrial Area Phase 2',
    status: 'UNDER INVESTIGATION',
    priority: 'MEDIUM'
  },
  {
    fir_id: 'FIR-2024-09264',
    date: '2024-12-03',
    district: 'Cyber City',
    crime_type: 'Cyber Fraud / Financial',
    hour: 15,
    day_of_week: 'Tuesday',
    is_weekend: false,
    latitude: 28.4920,
    longitude: 77.0860,
    description: 'Corporate email compromise (CEO fraud) directing wire transfer change of vendor banking details.',
    location_name: 'Udyog Vihar Phase 4',
    status: 'UNDER INVESTIGATION',
    priority: 'HIGH'
  },
  {
    fir_id: 'FIR-2024-09277',
    date: '2024-12-04',
    district: 'East District',
    crime_type: 'Robbery / Snatching',
    hour: 21,
    day_of_week: 'Wednesday',
    is_weekend: false,
    latitude: 28.6260,
    longitude: 77.2980,
    description: 'Purse snatching outside vegetable market by motorcycle riders fleeing into narrow bypass lanes.',
    location_name: 'Patparganj Residential Colony',
    status: 'CLOSED',
    priority: 'LOW'
  },
  {
    fir_id: 'FIR-2024-09289',
    date: '2024-12-05',
    district: 'West Outer',
    crime_type: 'Public Nuisance & Gambling',
    hour: 23,
    day_of_week: 'Thursday',
    is_weekend: false,
    latitude: 28.6530,
    longitude: 77.0630,
    description: 'Open drinking and noise disturbance resulting in public brawl outside highway commercial complex.',
    location_name: 'Dwarka Expressway Toll Sector 108',
    status: 'CLOSED',
    priority: 'LOW'
  },
  {
    fir_id: 'FIR-2024-09301',
    date: '2024-12-06',
    district: 'Central',
    crime_type: 'Vehicle Theft',
    hour: 20,
    day_of_week: 'Friday',
    is_weekend: false,
    latitude: 28.6320,
    longitude: 77.2190,
    description: 'Parked motorcycle lifted from unattended street near railway reservation counter.',
    location_name: 'New Delhi Station Ajmeri Gate',
    status: 'PENDING CHARGE',
    priority: 'MEDIUM'
  }
];

// Generate additional incidents to reach ~60 robust records
const ADDITIONAL_DESCRIPTIONS = [
  'Motorcycle snatching targeting pedestrian walking near dark arterial transit hub.',
  'Unlawful entry into locked retail shop overnight, cash register emptied.',
  'Online task-based part-time job scam siphoning payments via UPI QR code.',
  'Vehicle broken into and laptop bag removed from backseat after window smash.',
  'Street brawl between transport operators over parking queue rights.',
  'Narcotics distribution parcel seized during routine vehicle checkpoint inspection.',
  'Illegal betting operation running through encrypted instant messaging channels.',
  'Stolen luxury scooter dismantled for spare parts in local garage.',
  'SIM swap fraud initiated via compromised telecommunications vendor portal.',
  'Pedestrian intercepted at knife-point near pedestrian underpass at late hour.'
];

for (let i = 26; i <= 65; i++) {
  const district = DISTRICTS[i % DISTRICTS.length];
  const crime_type = CRIME_TYPES[(i * 3) % CRIME_TYPES.length];
  const hour = (i * 7) % 24;
  const is_weekend = i % 3 === 0;
  const baseCoord = DISTRICT_COORDS[district];
  const latOffset = ((i % 7) - 3) * 0.005;
  const lngOffset = (((i + 2) % 7) - 3) * 0.005;

  MOCK_INCIDENTS.push({
    fir_id: `FIR-2024-09${300 + i}`,
    date: `2024-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 27) + 1).padStart(2, '0')}`,
    district,
    crime_type,
    hour,
    day_of_week: is_weekend ? (i % 2 === 0 ? 'Saturday' : 'Sunday') : ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'][i % 5],
    is_weekend,
    latitude: +(baseCoord.lat + latOffset).toFixed(4),
    longitude: +(baseCoord.lng + lngOffset).toFixed(4),
    description: ADDITIONAL_DESCRIPTIONS[i % ADDITIONAL_DESCRIPTIONS.length],
    location_name: `${district} Sector ${10 + (i % 30)} Corridor`,
    status: ['UNDER INVESTIGATION', 'PENDING CHARGE', 'CLOSED', 'COURT TRIAL'][i % 4] as any,
    priority: hour >= 22 || hour <= 4 ? 'HIGH' : (i % 2 === 0 ? 'MEDIUM' : 'LOW')
  });
}
